changelog:
  categories:
    - title: Features
      labels:
        - feat
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
  exclude:
    labels:
      - skip-changelog
